function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 05-May-2017 10:57:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Parent',axes1);

% Create xlabel
xlabel('velocidad [knot]');

% Create ylabel
ylabel('Traccion [lbf]');

grid(axes1,'on');
